### PR TITLE
Convert to netstandard1.0

### LINKED ISSUE #10: dotnet core version of FeatureSwitcher
I really want this lib for the .Net Core Framework. 
[https://www.microsoft.com/net/core](url)

The best would be that it have very few dependencies to other libs and following the .NET Standard Platform Version 1.6
[https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md](url)

### PR DESCRIPTION
**Pull request by robertcoltheart**
My F# is not the greatest, so the build script needs a bit of scrutiny, but the rest of the code should be fine. I'm also not super clear on how the version is being passed from Github to the build script. Please take a look 👍 

Notes:
The mspec tests had to be reorganised a bit so as to get the test runner working. Not sure why it had to be done like that.

Fixes #10

### CODE REVIEW

**Comment by jonnii** [comment]
@robertcoltheart @mexx thanks for doing the work on this! This is one of the dependencies we need to get our project ported to .netcore. Could we merge and release this?

**Comment by robertcoltheart** [comment]
@mexx Any update on this?

**Comment by mexx** [comment]
Hey guys!

At first I want to thank you for the PR, the conversion was always on my plate, but I didn't have time and need to.

However as I tried to tackle the PR, I recognised that the release process is not automated at all, I don't remember the steps needed, and as well my build infrastructure is not present anymore.
So please give me some time to setup the project in the right way, using AppVeyor and Travis CI for the builds, as well as adding a release automation.

Further an integration test is needed for the new target, to decide whether this change in target is backwards-compatible or not. To version the package properly according to the semantic versioning.

**Comment by jonnii** [comment]
@mexx if you want I'm happy to help with some of that - i use gitversion and appveyor on my own repos.

**Comment by robertcoltheart** [comment]
Yep, me too. Also use Travis CI, so I can certainly help as well.

**Comment by robertcoltheart** [comment]
Thanks!

**Pull request closed without merging**
